//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onetour2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividades
    {
        public int id_actividad { get; set; }
        public int id_curso { get; set; }
        public string tipo_actividad { get; set; }
        public int monto_recaudado { get; set; }
    
        public virtual curso curso { get; set; }
    }
}
