//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onetour2.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LaboratorioEntities : DbContext
    {
        public LaboratorioEntities()
            : base("name=LaboratorioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividades> actividades { get; set; }
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<apoderado> apoderado { get; set; }
        public virtual DbSet<colegio> colegio { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<cuenta_alumno> cuenta_alumno { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<depositos> depositos { get; set; }
        public virtual DbSet<fondo_común> fondo_común { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<representante> representante { get; set; }
        public virtual DbSet<seguros> seguros { get; set; }
        public virtual DbSet<seguros_contratados> seguros_contratados { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    
        public virtual int Sp_actualizarCuentaAlumno(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_actualizarCuentaAlumno", aParameter, bParameter);
        }
    
        public virtual ObjectResult<Sp_reporte_CuentaAlumno_Result> Sp_reporte_CuentaAlumno(string a)
        {
            var aParameter = a != null ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_reporte_CuentaAlumno_Result>("Sp_reporte_CuentaAlumno", aParameter);
        }
    
        public virtual ObjectResult<Sp_reporte_InfoAlumno_Result> Sp_reporte_InfoAlumno(string a)
        {
            var aParameter = a != null ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_reporte_InfoAlumno_Result>("Sp_reporte_InfoAlumno", aParameter);
        }
    
        public virtual int Sp_actualizarFondoComún(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_actualizarFondoComún", aParameter, bParameter);
        }
    
        public virtual int Sp_actualizarUsuario(Nullable<int> a, string b, string c)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b != null ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(string));
    
            var cParameter = c != null ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_actualizarUsuario", aParameter, bParameter, cParameter);
        }
    
        public virtual int Sp_actualizarSaldoCuentaAlumno(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_actualizarSaldoCuentaAlumno", aParameter, bParameter);
        }
    
        public virtual int Sp_AgregarSeguroVida(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_AgregarSeguroVida", aParameter, bParameter);
        }
    
        public virtual int Sp_EliminarSeguroVida(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_EliminarSeguroVida", aParameter, bParameter);
        }
    
        public virtual int Sp_AgregarSeguroViaje(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_AgregarSeguroViaje", aParameter, bParameter);
        }
    
        public virtual int Sp_EliminarSeguroVije(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_EliminarSeguroVije", aParameter, bParameter);
        }
    }
}
