//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onetour2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        public int id_contrato { get; set; }
        public int id_colegio { get; set; }
        public int id_curso { get; set; }
        public int monto_final { get; set; }
        public int cantidad_alumnos { get; set; }
        public string destino { get; set; }
        public System.DateTime fecha_viaje { get; set; }
        public System.DateTime fecha_tope { get; set; }
        public Nullable<int> id_seguros_contratados { get; set; }
        public byte[] contrato1 { get; set; }
    
        public virtual colegio colegio { get; set; }
        public virtual curso curso { get; set; }
        public virtual curso curso1 { get; set; }
    }
}
